### ISSUE TITLE
AndroidManifest allowBackup attribute override not possible

### ISSUE THREAD

**Issue by arkadiuszrutkowski** [jrejaud/ViewPagerIndicator2#1]
Hello.

Not sure if bug but when I set allowBackup to 'false' in my manifest, the project can not build properly:

Error:Execution failed for task ':app:processDebugManifest'.

> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:27:9-36
>     is also present at [com.github.jrejaud:ViewPagerIndicator2:0.0.1] AndroidManifest.xml:12:9-35 value=(true).
>     Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:22:5-62:19 to override.

**Comment by jrejaud** [comment]
Does this issue also occur when you use the original viewpagerindicator? https://github.com/JakeWharton/ViewPagerIndicator

**Comment by arkadiuszrutkowski** [comment]
No, it doesn't. Probably you have to remove < application /> tag from ViewPagerIndicator2's manifest and that will be fine.

**Comment by jrejaud** [comment]
If you fix it and make a PR, I'll pull it in :)

**Comment by arkadiuszrutkowski** [comment]
Sure will do it in spare time. :)
