### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by kkocel** [jrejaud/ViewPagerIndicator2#5]
Hey,
I've found that in library that there is `android:supportsRtl` element which is not present in current master.

This results in warning during build:

```
> Manifest merger failed : Attribute application@supportsRtl value=(false) from AndroidManifest.xml:14:9-36
    is also present at [com.github.jrejaud:ViewPagerIndicator2:0.0.1] AndroidManifest.xml:14:9-35 value=(true).
    Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:4:5-71:19 to override.
```

Is there a possibility to release a new version without this attribute?

**Comment by jrejaud** [comment]
Can you provide a pull request where you remove this attribute? I'll merge it in.

**Comment by kkocel** [comment]
@jrejaud  AFAIK this is alreade merged. Did you released new version after merges?

**Comment by jrejaud** [comment]
Slipped my mind, I created a new release with merged changes.
